services:
  mysql:
    image: mysql:8
    container_name: customer_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customer_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: